name: Deploy Python project to function app

on:
  push:
    branches: [ "main" ]

env:
  AZURE_RESOURCEGROUP_NAME: CRC
  AZURE_FUNCTIONAPP_NAME: azurecrcAPI # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'   # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.9'                 # set this to the Python version
  
jobs:
  # This workflow contains 2 jobs, first it deploys the infrastructure then it deploys the function app
  build-and-deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Depoy DB ARM Template    
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./infrastructure/azuredeploydb.json
        parameters: ./infrastructure/azuredeploydb.parameters.json

    - name: Depoy Function ARM Template    
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./infrastructure/azuredeployfunc.json
        parameters: ./infrastructure/azuredeployfunc.parameters.json
        

  build-and-deploy-function-app:
    needs: build-and-deploy-infrastructure
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd
    
    ## uncomment to run python tests once I figure out why azure.data.tables module isn't being found
    #- name: 'Run Python Tests'
    #  run: python -m unittest discover azurecrcAPI

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
